### ISSUE TITLE
The scraping never stops

### ISSUE THREAD

**Issue by adnan007d** [ricardoprins/scraping-jobs-for-alex#1]
For some strange reason it never stops running, I looked up the website and lit stores the meta-data in a script tag, I made a script which scrapes from it

**Comment by mar-galho** [comment]
it's still not ready - I'm playing with it in order to figure out ways of scraping a large volume of data while avoiding the website's protective measures. 

I'll let you know when i'm done with fiddling with it - today I was able to scrape 3500 jobs before being blocked XD

**Comment by adnan007d** [comment]
I didn't see that next page feature that explains why it runs for so long

**Comment by mar-galho** [comment]
Yeah, i'm testing how many requests I can make before I'm banned, and then looking for ways to avoid it: whether be it by changing headers, extending the timer, and things like that. This repo (and the next ones) will be a part of a series of tutorials I'm going to launch about webscraping - from zero to hero lol.

Feel free to contribute with ideas and suggestions though - and, if you want to go ahead you can create a scraper for Monster Jobs (I'm almost done with Indeed). Try doing it without using Selenium though - I'm trying not to use Selenium at this point.

**Comment by adnan007d** [comment]
Solved!!
